#!/usr/bin/env python3
"""
Python STREAM reference values for test/test_heat_diffusion.jl.

Evaluates `Fuel.calculate` at one fixed state in four cases and writes the cell temperature
derivatives, with every input, to test/data/heat_diffusion_reference.jl:

  clad_x    clad-meat-clad plate on a non-uniform mesh, a contact between clad and meat,
            convective walls on both faces (x_diffusion)
  clad_xz   the same with axial conduction and convective top and bottom (xz_diffusion)
  rod_r     UO2 pellet in Zircaloy, a pellet-clad gap as a contact, cooled outside (r_diffusion)
  rod_rz    the same with axial conduction (rz_diffusion)

Not run in CI. Rerun by hand when Python's heat diffusion changes:

  cd test && STREAM_PATH=path/to/STREAM python generate_heat_reference.py

STREAM_PATH defaults to ~/projects/STREAM, as in generate_mtr_reference.py.
"""

import os
import sys

import numpy as np

STREAM_PATH = os.environ.get("STREAM_PATH", os.path.expanduser("~/projects/STREAM"))
sys.path.insert(0, STREAM_PATH)

from stream.calculations.heat_diffusion import Fuel, Solid, r_diffusion, rz_diffusion, x_diffusion, xz_diffusion  # noqa: E402
from stream.composition.mtr_geometry import x_boundaries  # noqa: E402

rng = np.random.default_rng(20261004)


def jl(a):
    """A numpy array or number as a Julia literal, full precision."""
    a = np.asarray(a, dtype=float)
    f = lambda v: "Inf" if np.isinf(v) else repr(float(v))  # noqa: E731
    if a.ndim == 0:
        return f(a)
    if a.ndim == 1:
        return "[" + ", ".join(map(f, a)) + "]"
    return "[" + "; ".join(" ".join(map(f, row)) for row in a) + "]"


def case(name, heat_func, z, x, materials, meat, x_contacts, y, power, walls):
    shape = (len(z) - 1, len(x) - 1)
    m, n = shape
    full_shape = np.zeros(shape)
    full_shape[meat] = rng.uniform(0.5, 1.5, meat.sum())
    full_shape /= full_shape.sum()
    fuel = Fuel(
        z_boundaries=z,
        x_boundaries=x,
        material=Solid.from_array(materials),
        y_length=y,
        power_shape=full_shape[meat],
        heat_func=heat_func,
        x_contacts=x_contacts,
        meat_indices=meat.astype(int),
        name=name,
    )
    T = rng.uniform(40.0, 90.0, shape)
    state = np.concatenate([T.flatten(), np.zeros(2 * m)])
    dT = fuel.save(fuel.calculate(state, power=power, **walls))["T"]
    kw = {k: jl(v) for k, v in walls.items()}
    fields = dict(
        z=jl(z), x=jl(x),
        rho=jl(fuel.material.density), cp=jl(fuel.material.specific_heat), k=jl(fuel.material.conductivity),
        x_contacts=jl(x_contacts), y=jl(y), power=jl(power), power_shape=jl(full_shape),
        T=jl(T), dT=jl(dT), **kw,
    )
    body = ",\n        ".join(f"{k} = {v}" for k, v in fields.items())
    return f"    {name} = (\n        {body},\n    ),\n"


# Plate: 2 clad cells, 3 meat cells, 2 clad cells, on an uneven axial mesh.
clad, meat_solid = Solid(2700.0, 900.0, 250.0), Solid(3000.0, 800.0, 100.0)
x_plate = x_boundaries(2, 3, 0.4e-3, 0.5e-3)
z_plate = np.array([0.0, 0.1, 0.25, 0.4])
m, n = len(z_plate) - 1, len(x_plate) - 1
meat_plate = np.zeros((m, n), dtype=bool)
meat_plate[:, 2:5] = True
mat_plate = np.where(meat_plate, meat_solid, clad)
xc_plate = np.full((m, n + 1), np.inf)
xc_plate[:, 2] = 3.0e4  # left clad-meat interface
walls_x = dict(
    T_left=rng.uniform(30, 50, m), h_left=rng.uniform(1e4, 3e4, m),
    T_right=rng.uniform(30, 50, m), h_right=rng.uniform(1e4, 3e4, m),
)
walls_z = dict(
    T_top=rng.uniform(30, 50, n), h_top=rng.uniform(1e3, 5e3, n),
    T_bottom=rng.uniform(30, 50, n), h_bottom=rng.uniform(1e3, 5e3, n),
)

# Rod: 4 pellet cells, 2 clad cells, a gap conductance between them, cooled outside only.
uo2, zr = Solid(10400.0, 300.0, 3.0), Solid(6500.0, 330.0, 16.0)
r_rod = np.array([0.0, 1.5e-3, 2.7e-3, 3.5e-3, 4.1e-3, 4.45e-3, 4.75e-3])
z_rod = np.array([0.0, 0.2, 0.5, 0.7])
m, n = len(z_rod) - 1, len(r_rod) - 1
meat_rod = np.zeros((m, n), dtype=bool)
meat_rod[:, :4] = True
mat_rod = np.where(meat_rod, uo2, zr)
xc_rod = np.full((m, n + 1), np.inf)
xc_rod[:, 4] = 5.0e3  # pellet-clad gap
walls_r = dict(T_right=rng.uniform(30, 50, m), h_right=rng.uniform(2e4, 4e4, m))
walls_rz = walls_r | dict(
    T_top=rng.uniform(30, 50, n), h_top=rng.uniform(1e3, 5e3, n),
    T_bottom=rng.uniform(30, 50, n), h_bottom=rng.uniform(1e3, 5e3, n),
)

out = [
    "# Generated by test/generate_heat_reference.py from Python STREAM. Do not edit by hand.\n",
    "# Each case holds Fuel's inputs and the cell temperature derivatives dT it returns.\n",
    "const HEAT_REFERENCE = (\n",
    case("clad_x", x_diffusion, z_plate, x_plate, mat_plate, meat_plate, xc_plate, 0.07, 800.0, walls_x),
    case("clad_xz", xz_diffusion, z_plate, x_plate, mat_plate, meat_plate, xc_plate, 0.07, 800.0, walls_x | walls_z),
    case("rod_r", r_diffusion, z_rod, r_rod, mat_rod, meat_rod, xc_rod, 1.0, 5000.0, walls_r),
    case("rod_rz", rz_diffusion, z_rod, r_rod, mat_rod, meat_rod, xc_rod, 1.0, 5000.0, walls_rz),
    ")\n",
]
path = os.path.join(os.path.dirname(__file__), "data", "heat_diffusion_reference.jl")
with open(path, "w") as f:
    f.write("".join(out))
print(f"wrote {path}")
