# test/runtests.jl — thin orchestrator

include("preamble.jl")

include("test_geometry.jl")
include("test_knobs.jl")
include("test_connectors.jl")
include("test_substances.jl")
include("test_channels.jl")
include("test_pump.jl")
include("test_flapper.jl")
include("test_resistors.jl")
include("test_ideal.jl")
include("test_heat_diffusion.jl")
include("test_determinacy.jl")
include("test_correlations.jl")
include("test_htc.jl")
include("test_thresholds.jl")
include("test_composition.jl")
include("test_utilities.jl")
include("test_solvers.jl")
include("test_examples.jl")
include("test_validation.jl")
include("test_integration.jl")
include("test_point_kinetics.jl")
