# test/runtests.jl — thin orchestrator
# All test logic lives in the individual test_*.jl files.
include("test_geometry.jl")
include("test_connectors.jl")
include("test_fluids.jl")
include("test_channel.jl")
include("test_sign_safety.jl")
include("test_pump.jl")
include("test_flapper.jl")
include("test_resistors.jl")
include("test_misc.jl")
include("test_heat_diffusion.jl")
include("test_correlations.jl")
include("test_subcooled_boiling.jl")
include("test_composition.jl")
include("test_solvers.jl")
include("test_validation.jl")
include("test_examples.jl")
include("test_loss_of_flow.jl")
include("test_analysis.jl")
