# test/data/python_parity_reference.jl
# Python-STREAM parity reference values — tiers (a)+(b)+(c)+(d).
#
# Generated by:
#   - test/generate_reference.py        (simple-loop scenario)
#   - test/generate_mtr_reference.py    (MTR symmetric / asymmetric / one-sided)
# Regenerate at reference-update time with:
#   cd test && python3 generate_reference.py
#   cd test && python3 generate_mtr_reference.py
# then paste the bracketed sections back into this file (or re-run the generator).
#
# Python is NOT in CI. This file is the cached reference;
# regeneration is a manual developer-machine step.
#
# Separate-file path (NOT inline in test_validation.jl) because
# the const-block size dwarfs test logic.
#
# Consumed by test/test_validation.jl via:
#   include(joinpath(@__DIR__, "data", "python_parity_reference.jl"))

# Block 0 — MTR rectangular geometry (shared across symmetric/asymmetric/one-sided)
# Rectangular MTR: L=0.6, edge1=0.07, edge2=0.00127, heated_edge=0.07
# Computed: Dh = 4*area/wet_perim ~= 0.002495 m; both faces heated.
const PARITY_MTR_GEOM_DH = 2.4947383191e-03
const PARITY_MTR_GEOM_AREA = 8.8900000000e-05
const PARITY_MTR_GEOM_WETPERIM = 1.4254000000e-01
const PARITY_MTR_GEOM_HEATED = (7.0000000000e-02, 7.0000000000e-02)

# Block 1 — Simple loop (Pump → HX → CAC → Pump, n=10, circular pipe)
# Topology: matches generate_reference.py current scenario.
# Adiabatic-side convention: T_wall_left = T_cool, q_density_left = 0;
# h_left mirrors h_right (Python _other_if_none HTC convention).
# heated_parts partition differs Python (πD,0) vs Julia (πD/2, πD/2);
# parity testsets compare TOTAL q_wall (left+right) where applicable.
# Simple-loop Python parity reference — tiers (a)+(b)+(c)
# Topology: Pump → HX → ChannelAndContacts (n=10, L=0.6, D=0.01) → Pump
# T_inlet = 40.0 °C; T_wall = 100.0 °C
# Solver: scipy.optimize.root (default xtol=1.49e-8)

const PARITY_SIMPLE_T_OUT = 54.6394342808
const PARITY_SIMPLE_ṁ = 0.6092891722
const PARITY_SIMPLE_DP = 30000.0000000000

const PARITY_SIMPLE_T_CELLS = Float64[
    41.6231541132,  # T[1]
    43.2098119790,  # T[2]
    44.7603537855,  # T[3]
    46.2751838982,  # T[4]
    47.7547290373,  # T[5]
    49.1994362781,  # T[6]
    50.6097711217,  # T[7]
    51.9862156421,  # T[8]
    53.3292667077,  # T[9]
    54.6394342808,  # T[10]
]

const PARITY_SIMPLE_T_WALL_LEFT = Float64[
    100.0000000000,  # T_wall_left[1]
    100.0000000000,  # T_wall_left[2]
    100.0000000000,  # T_wall_left[3]
    100.0000000000,  # T_wall_left[4]
    100.0000000000,  # T_wall_left[5]
    100.0000000000,  # T_wall_left[6]
    100.0000000000,  # T_wall_left[7]
    100.0000000000,  # T_wall_left[8]
    100.0000000000,  # T_wall_left[9]
    100.0000000000,  # T_wall_left[10]
]

const PARITY_SIMPLE_T_WALL_RIGHT = Float64[
    100.0000000000,  # T_wall_right[1]
    100.0000000000,  # T_wall_right[2]
    100.0000000000,  # T_wall_right[3]
    100.0000000000,  # T_wall_right[4]
    100.0000000000,  # T_wall_right[5]
    100.0000000000,  # T_wall_right[6]
    100.0000000000,  # T_wall_right[7]
    100.0000000000,  # T_wall_right[8]
    100.0000000000,  # T_wall_right[9]
    100.0000000000,  # T_wall_right[10]
]

const PARITY_SIMPLE_H_TC_LEFT = Float64[
    37559.9808693911,  # h_left[1]
    37744.1354419077,  # h_left[2]
    37923.4750153102,  # h_left[3]
    38098.0889739943,  # h_left[4]
    38268.0677140248,  # h_left[5]
    38433.5023986780,  # h_left[6]
    38594.4847305045,  # h_left[7]
    38751.1067394002,  # h_left[8]
    38903.4605861303,  # h_left[9]
    39051.6383807207,  # h_left[10]
]

const PARITY_SIMPLE_H_TC_RIGHT = Float64[
    37559.9808693911,  # h_right[1]
    37744.1354419077,  # h_right[2]
    37923.4750153102,  # h_right[3]
    38098.0889739943,  # h_right[4]
    38268.0677140248,  # h_right[5]
    38433.5023986780,  # h_right[6]
    38594.4847305045,  # h_right[7]
    38751.1067394002,  # h_right[8]
    38903.4605861303,  # h_right[9]
    39051.6383807207,  # h_right[10]
]

const PARITY_SIMPLE_Q_DENSITY_LEFT = Float64[
    2192633.2147222073,  # q_density_left  # W/m^2[1]
    2143496.5484349420,  # q_density_left  # W/m^2[2]
    2094879.3430695115,  # q_density_left  # W/m^2[3]
    2046812.8239595154,  # q_density_left  # W/m^2[4]
    1999325.5669365132,  # q_density_left  # W/m^2[5]
    1952443.5876608421,  # q_density_left  # W/m^2[6]
    1906190.4342793541,  # q_density_left  # W/m^2[7]
    1860587.2826155813,  # q_density_left  # W/m^2[8]
    1815653.0331625440,  # q_density_left  # W/m^2[9]
    1771404.4092118021,  # q_density_left  # W/m^2[10]
]

const PARITY_SIMPLE_Q_DENSITY_RIGHT = Float64[
    2192633.2147222073,  # q_density_right # W/m^2[1]
    2143496.5484349420,  # q_density_right # W/m^2[2]
    2094879.3430695115,  # q_density_right # W/m^2[3]
    2046812.8239595154,  # q_density_right # W/m^2[4]
    1999325.5669365132,  # q_density_right # W/m^2[5]
    1952443.5876608421,  # q_density_right # W/m^2[6]
    1906190.4342793541,  # q_density_right # W/m^2[7]
    1860587.2826155813,  # q_density_right # W/m^2[8]
    1815653.0331625440,  # q_density_right # W/m^2[9]
    1771404.4092118021,  # q_density_right # W/m^2[10]
]


# Block 2 — MTR symmetric (both inlets at 40.0 °C)
# Adiabatic-side convention: each channel's outer wall (channel_L's LEFT,
# channel_R's RIGHT) is adiabatic — T_wall = T_cool, q_density = 0.
# Symmetric MTR: T_inlet_l = T_inlet_r = 40.0 °C; power = 10000.0 W
const PARITY_MTR_SYM_T_OUT_L = 44.7370777964
const PARITY_MTR_SYM_T_OUT_R = 44.7370777964
const PARITY_MTR_SYM_ṁ_L = 0.2525471427
const PARITY_MTR_SYM_ṁ_R = 0.2525471427
const PARITY_MTR_SYM_DP = 30000.0000000000

const PARITY_MTR_SYM_T_CELLS_L = Float64[
    40.4737563175,  # T_l[1]
    40.9475027955,  # T_l[2]
    41.4212390674,  # T_l[3]
    41.8949647834,  # T_l[4]
    42.3686795933,  # T_l[5]
    42.8423831464,  # T_l[6]
    43.3160750925,  # T_l[7]
    43.7897550818,  # T_l[8]
    44.2634227655,  # T_l[9]
    44.7370777964,  # T_l[10]
]

const PARITY_MTR_SYM_T_CELLS_R = Float64[
    40.4737563175,  # T_r[1]
    40.9475027955,  # T_r[2]
    41.4212390674,  # T_r[3]
    41.8949647834,  # T_r[4]
    42.3686795933,  # T_r[5]
    42.8423831464,  # T_r[6]
    43.3160750925,  # T_r[7]
    43.7897550818,  # T_r[8]
    44.2634227655,  # T_r[9]
    44.7370777964,  # T_r[10]
]

const PARITY_MTR_SYM_T_WALL_LEFT_L = Float64[
    40.4737563175,
    40.9475027955,
    41.4212390674,
    41.8949647834,
    42.3686795933,
    42.8423831464,
    43.3160750925,
    43.7897550818,
    44.2634227655,
    44.7370777964,
]

const PARITY_MTR_SYM_T_WALL_RIGHT_L = Float64[
    46.9945441043,
    47.4431412959,
    47.8919580306,
    48.3409911364,
    48.7902374823,
    49.2396939783,
    49.6893575788,
    50.1392252843,
    50.5892941243,
    51.0395611880,
]

const PARITY_MTR_SYM_H_TC_LEFT_L = Float64[
    18256.6313980564,
    18327.3159414731,
    18397.8966972735,
    18468.3730019591,
    18538.7442032052,
    18609.0096599326,
    18679.1687433753,
    18749.2208372455,
    18819.1653331383,
    18889.0016386591,
]

const PARITY_MTR_SYM_H_TC_RIGHT_L = Float64[
    18256.6313980564,
    18327.3159414731,
    18397.8966972735,
    18468.3730019591,
    18538.7442032052,
    18609.0096599326,
    18679.1687433753,
    18749.2208372455,
    18819.1653331383,
    18889.0016386591,
]

const PARITY_MTR_SYM_Q_LEFT_L = Float64[
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
]

const PARITY_MTR_SYM_Q_RIGHT_L = Float64[
    119047.6190471115,
    119047.6190380509,
    119047.6190415378,
    119047.6190668410,
    119047.6190908585,
    119047.6190678767,
    119047.6190117348,
    119047.6190254099,
    119047.6189775529,
    119047.6191114420,
]

const PARITY_MTR_SYM_T_WALL_LEFT_R = Float64[
    46.9945441043,
    47.4431412959,
    47.8919580306,
    48.3409911364,
    48.7902374823,
    49.2396939783,
    49.6893575788,
    50.1392252843,
    50.5892941243,
    51.0395611880,
]

const PARITY_MTR_SYM_T_WALL_RIGHT_R = Float64[
    40.4737563175,
    40.9475027955,
    41.4212390674,
    41.8949647834,
    42.3686795933,
    42.8423831464,
    43.3160750925,
    43.7897550818,
    44.2634227655,
    44.7370777964,
]

const PARITY_MTR_SYM_H_TC_LEFT_R = Float64[
    18256.6313980564,
    18327.3159414731,
    18397.8966972735,
    18468.3730019591,
    18538.7442032052,
    18609.0096599326,
    18679.1687433753,
    18749.2208372455,
    18819.1653331383,
    18889.0016386591,
]

const PARITY_MTR_SYM_H_TC_RIGHT_R = Float64[
    18256.6313980564,
    18327.3159414731,
    18397.8966972735,
    18468.3730019591,
    18538.7442032052,
    18609.0096599326,
    18679.1687433753,
    18749.2208372455,
    18819.1653331383,
    18889.0016386591,
]

const PARITY_MTR_SYM_Q_LEFT_R = Float64[
    119047.6190471115,
    119047.6190380509,
    119047.6190415378,
    119047.6190668410,
    119047.6190908585,
    119047.6190678767,
    119047.6190117348,
    119047.6190254099,
    119047.6189775529,
    119047.6191114420,
]

const PARITY_MTR_SYM_Q_RIGHT_R = Float64[
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
]

const PARITY_MTR_SYM_T_PLATE = Float64[
    47.1205361678 47.2045308767 47.1205361678;  # row z=1
    47.5691333594 47.6531280684 47.5691333594;  # row z=2
    48.0179500941 48.1019448031 48.0179500941;  # row z=3
    48.4669831999 48.5509779089 48.4669831999;  # row z=4
    48.9162295458 49.0002242548 48.9162295458;  # row z=5
    49.3656860418 49.4496807508 49.3656860418;  # row z=6
    49.8153496423 49.8993443513 49.8153496423;  # row z=7
    50.2652173478 50.3492120568 50.2652173478;  # row z=8
    50.7152861878 50.7992808968 50.7152861878;  # row z=9
    51.1655532515 51.2495479605 51.1655532515;  # row z=10
]  # size (10, 3)


# Block 3 — MTR asymmetric (right inlet 90.0 °C)
# Asymmetric MTR: T_inlet_l = 40.0 °C, T_inlet_r = 90.0 °C
const PARITY_MTR_ASYM_T_OUT_L = 58.3252122088
const PARITY_MTR_ASYM_T_OUT_R = 81.5217595024
const PARITY_MTR_ASYM_ṁ_L = 0.2572137154
const PARITY_MTR_ASYM_ṁ_R = 0.2724600480
const PARITY_MTR_ASYM_DP = 30000.0000000000

const PARITY_MTR_ASYM_T_CELLS_L = Float64[
    42.3300576408,  # T_l[1]
    44.5288511958,  # T_l[2]
    46.6049619500,  # T_l[3]
    48.5664816389,  # T_l[4]
    50.4210296767,  # T_l[5]
    52.1757717167,  # T_l[6]
    53.8374390947,  # T_l[7]
    55.4123488165,  # T_l[8]
    56.9064236625,  # T_l[9]
    58.3252122088,  # T_l[10]
]

const PARITY_MTR_ASYM_T_CELLS_R = Float64[
    88.6870869849,  # T_r[1]
    87.4967162492,  # T_r[2]
    86.4209490021,  # T_r[3]
    85.4522888910,  # T_r[4]
    84.5836681611,  # T_r[5]
    83.8084321891,  # T_r[6]
    83.1203229174,  # T_r[7]
    82.5134616532,  # T_r[8]
    81.9823314713,  # T_r[9]
    81.5217595024,  # T_r[10]
]

const PARITY_MTR_ASYM_T_WALL_LEFT_L = Float64[
    42.3300576408,
    44.5288511958,
    46.6049619500,
    48.5664816389,
    50.4210296767,
    52.1757717167,
    53.8374390947,
    55.4123488165,
    56.9064236625,
    58.3252122088,
]

const PARITY_MTR_ASYM_T_WALL_RIGHT_L = Float64[
    71.3930599626,
    71.7116188178,
    72.0557852439,
    72.4214549849,
    72.8050986248,
    73.2036903297,
    73.6146436955,
    74.0357554252,
    74.4651530434,
    74.9012510058,
]

const PARITY_MTR_ASYM_H_TC_LEFT_L = Float64[
    20519.2964830188,
    20705.0395140286,
    20882.7183819765,
    21052.7277189891,
    21215.4606544892,
    21371.3052199268,
    21520.6414524621,
    21663.8393318340,
    21801.2567246992,
    21933.2383487948,
]

const PARITY_MTR_ASYM_H_TC_RIGHT_L = Float64[
    20519.2964830188,
    20705.0395140286,
    20882.7183819765,
    21052.7277189891,
    21215.4606544892,
    21371.3052199268,
    21520.6414524621,
    21663.8393318340,
    21801.2567246992,
    21933.2383487948,
]

const PARITY_MTR_ASYM_Q_LEFT_L = Float64[
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
]

const PARITY_MTR_ASYM_Q_RIGHT_L = Float64[
    596352.3613271451,
    562820.2777153560,
    531482.3754372145,
    502212.2585972577,
    474888.3340561311,
    449394.0668193924,
    425618.1291449066,
    403454.4885813470,
    382802.3669935331,
    363566.2098127098,
]

const PARITY_MTR_ASYM_T_WALL_LEFT_R = Float64[
    74.4239450727,
    74.5295752005,
    74.6747459514,
    74.8545504509,
    75.0646871634,
    75.3013902644,
    75.5613664425,
    75.8417390493,
    76.1399956972,
    76.4539440620,
]

const PARITY_MTR_ASYM_T_WALL_RIGHT_R = Float64[
    88.6870869849,
    87.4967162492,
    86.4209490021,
    85.4522888910,
    84.5836681611,
    83.8084321891,
    83.1203229174,
    82.5134616532,
    81.9823314713,
    81.5217595024,
]

const PARITY_MTR_ASYM_H_TC_LEFT_R = Float64[
    25117.6861088925,
    25042.1460031204,
    24977.1894614671,
    24922.0174493611,
    24875.8868572240,
    24838.1076585449,
    24808.0398976303,
    24785.0907811529,
    24768.7114896231,
    24758.3941393566,
]

const PARITY_MTR_ASYM_H_TC_RIGHT_R = Float64[
    25117.6861088925,
    25042.1460031204,
    24977.1894614671,
    24922.0174493611,
    24875.8868572240,
    24838.1076585449,
    24808.0398976303,
    24785.0907811529,
    24768.7114896231,
    24758.3941393566,
]

const PARITY_MTR_ASYM_Q_LEFT_R = Float64[
    -358257.1214759384,
    -324725.0393840054,
    -293387.1390501141,
    -264117.0223279473,
    -236793.0942942953,
    -211298.8231823852,
    -187522.8938137519,
    -165359.2504022747,
    -144707.1292159723,
    -125470.9720973205,
]

const PARITY_MTR_ASYM_Q_RIGHT_R = Float64[
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
]

const PARITY_MTR_ASYM_T_PLATE = Float64[
    72.0241995444 73.1184892901 74.0447896178;  # row z=1
    72.3072702784 73.3305837816 74.1859078669;  # row z=2
    72.6182707587 73.5752523701 74.3642445636;  # row z=3
    72.9529629594 73.8479894904 74.5750266034;  # row z=4
    73.3076887781 74.1448796666 74.8140811372;  # row z=5
    73.6792990490 74.4625270695 75.0777656721;  # row z=6
    74.0650895501 74.7979918415 75.3629047148;  # row z=7
    74.4627447594 75.1487340098 75.6667338421;  # row z=8
    74.8702855492 75.5125611428 75.9868473184;  # row z=9
    75.2860252453 75.8875843064 76.3211539495;  # row z=10
]  # size (10, 3)


# Block 4 — MTR one-sided (left channel only)
# KNOWN GAP: Python one_sided_connection distributes heat to BOTH plate
# faces (acknowledged Python bug). the one-sided parity testset compares Julia plate-T
# against analytical T_max formula, NOT Python plate-T values below.
# T_out_l Python value is also flagged as known-gap; the testset uses gray-zone
# tolerance for these specific quantities or asserts via analytical formula.
# One-sided MTR: only left channel; T_inlet_l = 40.0 °C
# KNOWN GAP:
#   Python one_sided_connection distributes heat to BOTH plate faces (acknowledged Python bug).
#   The one-sided testset compares Julia plate-T against the analytical T_max formula, NOT Python plate-T.
#   Tier (a) T_out_l is also flagged as known-gap; the testset documents the magnitude.
const PARITY_MTR_ONESIDED_T_OUT_L = 44.7370777987
const PARITY_MTR_ONESIDED_ṁ_L = 0.2525471427
const PARITY_MTR_ONESIDED_DP = 30000.0000000000

const PARITY_MTR_ONESIDED_T_CELLS_L = Float64[
    40.4737563181,  # T_l[1]
    40.9475027952,  # T_l[2]
    41.4212390664,  # T_l[3]
    41.8949647820,  # T_l[4]
    42.3686795917,  # T_l[5]
    42.8423831450,  # T_l[6]
    43.3160750915,  # T_l[7]
    43.7897550818,  # T_l[8]
    44.2634227664,  # T_l[9]
    44.7370777987,  # T_l[10]
]

const PARITY_MTR_ONESIDED_T_WALL_LEFT_L = Float64[
    46.9945441048,
    47.4431412958,
    47.8919580302,
    48.3409911358,
    48.7902374812,
    49.2396939763,
    49.6893575771,
    50.1392252845,
    50.5892941233,
    51.0395611918,
]

const PARITY_MTR_ONESIDED_T_WALL_RIGHT_L = Float64[
    40.4737563181,
    40.9475027952,
    41.4212390664,
    41.8949647820,
    42.3686795917,
    42.8423831450,
    43.3160750915,
    43.7897550818,
    44.2634227664,
    44.7370777987,
]

const PARITY_MTR_ONESIDED_H_TC_LEFT_L = Float64[
    18256.6313981034,
    18327.3159415845,
    18397.8966974964,
    18468.3730022326,
    18538.7442033347,
    18609.0096597744,
    18679.1687431654,
    18749.2208373757,
    18819.1653327219,
    18889.0016392049,
]

const PARITY_MTR_ONESIDED_H_TC_RIGHT_L = Float64[
    18256.6313981034,
    18327.3159415845,
    18397.8966974964,
    18468.3730022326,
    18538.7442033347,
    18609.0096597744,
    18679.1687431654,
    18749.2208373757,
    18819.1653327219,
    18889.0016392049,
]

const PARITY_MTR_ONESIDED_Q_LEFT_L = Float64[
    119047.6190468304,
    119047.6190429265,
    119047.6190542926,
    119047.6190835830,
    119047.6190986032,
    119047.6190560173,
    119047.6189953738,
    119047.6190313328,
    119047.6189385083,
    119047.6191422307,
]

const PARITY_MTR_ONESIDED_Q_RIGHT_L = Float64[
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
    0.0000000000,
]

const PARITY_MTR_ONESIDED_T_PLATE = Float64[
    47.1205361683 47.2045308773 47.1205361683;  # row z=1
    47.5691333593 47.6531280683 47.5691333593;  # row z=2
    48.0179500937 48.1019448027 48.0179500937;  # row z=3
    48.4669831993 48.5509779083 48.4669831993;  # row z=4
    48.9162295446 49.0002242536 48.9162295446;  # row z=5
    49.3656860398 49.4496807488 49.3656860398;  # row z=6
    49.8153496406 49.8993443496 49.8153496406;  # row z=7
    50.2652173480 50.3492120570 50.2652173480;  # row z=8
    50.7152861868 50.7992808958 50.7152861868;  # row z=9
    51.1655532553 51.2495479643 51.1655532553;  # row z=10
]  # size (10, 3)

