name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  code-style:
    permissions:
      contents: write
      checks: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Formatter & reviewdog
        uses: julia-actions/julia-format@v4
        with:
          version: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
